name: unittest

on:
  push:
    paths:
      - '**.py'
      - '**.pyx'

jobs:
  unittest_windows:
    runs-on: windows-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
          architecture: x64
      - name: Checkout reversi
        uses: actions/checkout@master
      - name: get python version
        run: python -V
      - name: Install requirements.txt
        run: |
             python -m pip install --upgrade pip
             pip install -r requirements.txt
      - name: unittest for python
        run: python -m unittest discover tests -v
  unittest_ubuntu:
    needs: unittest_windows
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
          architecture: x64
      - name: Checkout reversi
        uses: actions/checkout@master
      - name: get python version
        run: python -V
      - name: Install requirements.txt
        run: |
             python -m pip install --upgrade pip
             pip install -r requirements.txt
      - name: unittest for python
        run: |
          exec Xvfb :99 -screen 0 1366x768x16 &
          sleep 3
          export DISPLAY=:99
          python -m unittest discover tests -v
  unittest_macos:
    needs: unittest_windows
    runs-on: macos-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: x64
      - name: Checkout reversi
        uses: actions/checkout@master
      - name: get python version
        run: python -V
      - name: Install requirements.txt
        run: |
             python -m pip install --upgrade pip
             pip install -r requirements.txt
      - name: unittest for python
        run: python -m unittest discover tests -v
