name: unittest-master

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - '**.pyx'

jobs:
  unittest_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
          architecture: x64
      - name: Checkout reversi
        uses: actions/checkout@master
      - name: get python version
        run: python -V
      - name: Install requirements.txt
        run: |
             python -m pip install --upgrade pip
             pip install -r requirements.txt
      - name: unittest for python
        run: |
          exec Xvfb :99 -screen 0 1366x768x16 &
          sleep 3
          export DISPLAY=:99
          python -m unittest discover tests -v
