name: unittest_python_versions

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - '**.pyx'

jobs:
  unittest_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Checkout reversi
        uses: actions/checkout@master
      - name: get python version
        run: python -V
      - name: Install requirements.txt
        run: |
             python -m pip install --upgrade pip
             pip install -r requirements.txt
      - name: unittest for python
        run: python -m unittest discover tests -v
  unittest_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Checkout reversi
        uses: actions/checkout@master
      - name: get python version
        run: python -V
      - name: Install requirements.txt
        run: |
             python -m pip install --upgrade pip
             pip install -r requirements.txt
      - name: unittest for python
        run: |
          exec Xvfb :99 -screen 0 1366x768x16 &
          sleep 3
          export DISPLAY=:99
          python -m unittest discover tests -v
  unittest_macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Checkout reversi
        uses: actions/checkout@master
      - name: get python version
        run: python -V
      - name: Install requirements.txt
        run: |
             python -m pip install --upgrade pip
             pip install -r requirements.txt
      - name: unittest for python
        run: python -m unittest discover tests -v
